import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { ProductProvider } from "@/context/ProductContext";
import { CartPageProvider } from "@/context/CartPageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <CartPageProvider>
            <ProductProvider>{children}</ProductProvider>
          </CartPageProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
